### ISSUE TITLE
failure to connect to mariadb during docker-compose

### ISSUE THREAD

**Issue by JarEXE** [moe-lk/sis#75]
Hi, I'm trying to get the software running. 
After running `docker-compose up` i see the following errors 
`sis-mysql          | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'`

and then `sis-bulk-upload_1  | Trying to connect to mariadb at 172.18.0.3. Attempt 17`

Could you please advise? 

see screenshot.

![Screenshot from 2020-02-21 15 12 21](https://user-images.githubusercontent.com/50882116/75059909-a78f6980-54bc-11ea-92db-389fbbaa3c38.png)

**Comment by janithRS** [comment]
The issue is fixed [moe-lk/bulk-upload/pull/167] in this. Please follow the instructions on the .env.example file.

**Comment by Fuseteam** [comment]
@janithRS i assume it's not just rename to .env? i'm confused could you elaborate?
``` 
sis-bulk-upload_1  | Loading composer repositories with package information
sis-bulk-upload_1  | Installing dependencies (including require-dev) from lock file
sis-bulk-upload_1  | Nothing to install or update
sis-bulk-upload_1  | Package laracademy/model-generator is abandoned, you should avoid using it. Use laracademy/generators instead.
sis-bulk-upload_1  | Generating optimized autoload files
sis-bulk-upload_1  | > Illuminate\Foundation\ComposerScripts::postAutoloadDump
sis-bulk-upload_1  | > @php artisan package:discover --ansi
sis-bulk-upload_1  | The environment file is invalid!
sis-bulk-upload_1  | Failed to parse dotenv file due to an invalid name. Failed at [<html lang].
sis-bulk-upload_1  | Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
sis_sis-bulk-upload_1 exited with code 1
```

**Comment by janithRS** [comment]
Have you tried getting a pull? Most of the time the above error will appear due to the .env file. Since earlier we had no .env file in the repo. (Edit the db config if needed)

**Comment by Fuseteam** [comment]
@janithRS a pull from the repo? yes that was a fresh pull

**Comment by Fuseteam** [comment]
having tried a clean repo _and_ a clean image for completeness, the original error is back
this may or may not be related to
```
sis-mysql          | 2020-03-02 12:34:01+00:00 [Note] [Entrypoint]: Creating database openemis
sis-mysql          | 2020-03-02 12:34:01+00:00 [Note] [Entrypoint]: Creating user root
sis-mysql          | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%' sis-mysql exited with code 1

```
